add_newline = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ '
discharging_symbol = 'ğŸª£ '
disabled = false

[[battery.display]]
threshold = 0
style = 'bold yellow'

[git_status]
modified = "ğŸ“:${count} "
untracked = "âœ¨:${count} "
renamed = "ğŸ”ª:${count} "
ahead = "â†‘${count} "
behind = "â†“${count} "

[memory_usage]
threshold = 100
symbol = 'ï¡š'
style = "bold dimmed green"

[cmd_duration]
disabled = true

[status]
format = '[\[$status $symbol]]($style) '
disabled = false

[time]
disabled = true

[aws]
disabled = true

[custom.node_installed]
when = """ test -e package.json && test -d node_modules """
format = " need install packages(bold red)"

